AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RubyAlexaExample

  Sample SAM Template for RubyAlexaExample
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Resources:
  RubyLexLambdaExample:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: alexa_example/
      Handler: app.lambda_handler
      Runtime: ruby2.5
Outputs:
  RubyLexLambdaExample:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RubyLexLambdaExample.Arn
  RubyLexLambdaExampleIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RubyLexLambdaExampleRole.Arn
